# Breast Cancer Dataset Exploration

In this notebook, we will load and explore the Breast Cancer dataset from scikit-learn.
The goal is to understand the structure of the dataset before using it for machine learning classification.

This dataset contains measurements computed from images of breast mass cell nuclei.

Each row represents one sample.

Each sample has 30 numerical features, such as mean radius, mean texture, mean perimeter, and mean area.

The target label has two classes:

- 0 = malignant
- 1 = benign

The goal is to use the 30 features to predict whether a tumor is malignant or benign.

A malignant tumor is cancerous, while a benign tumor is non-cancerous.


We use `load_breast_cancer()` from scikit-learn to load the dataset.

In [1]:
import pandas as pd
from sklearn.datasets import load_breast_cancer

In [2]:
# Load the dataset
breast = load_breast_cancer()

# Create a DataFrame from the feature data
breast_dataset = pd.DataFrame(
    breast.data,
    columns=breast.feature_names
)

# Add the numeric label
breast_dataset["label"] = breast.target

# Add readable class names
breast_dataset["diagnosis"] = breast_dataset["label"].map({
    0: "Malignant",
    1: "Benign"
})

# Display first five rows
breast_dataset.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,label,diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0,Malignant
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0,Malignant
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0,Malignant
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0,Malignant
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0,Malignant

In [3]:
print("Dataset shape:", breast_dataset.shape)
print("Number of samples:", breast_dataset.shape[0])
print("Number of features:", len(breast.feature_names))

print("\nTarget names:")
print(breast.target_names)

Dataset shape: (569, 32)
Number of samples: 569
Number of features: 30

Target names:
['malignant' 'benign']

## Class Distribution

We count how many samples belong to each class.

This helps us understand whether the dataset is balanced or imbalanced.

In [4]:
breast_dataset["diagnosis"].value_counts()

diagnosis
Benign       357
Malignant    212
Name: count, dtype: int64

In [5]:
breast_dataset.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,label,diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0,Malignant
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0,Malignant
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0,Malignant
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0,Malignant
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0,Malignant

Remark: The original dataset has 30 input features.

After creating the DataFrame, we added two extra columns:

- label: the numeric target value
- diagnosis: the readable target name

Therefore, the final DataFrame has 32 columns: 30 features + 2 label columns.